#include <gssapi.h>
#include <gssapi/gssapi_krb5.h>

const OM_uint32 _GSS_C_INDEFINITE = GSS_C_INDEFINITE;
const OM_uint32 _GSS_S_CONTINUE_NEEDED = GSS_S_CONTINUE_NEEDED;
const OM_uint32 _GSS_C_CALLING_ERROR_MASK = GSS_C_CALLING_ERROR_MASK;
const OM_uint32 _GSS_C_ROUTINE_ERROR_MASK = GSS_C_ROUTINE_ERROR_MASK;
